# Minimale golangci-lint Konfiguration für v2.x Kompatibilität
# Siehe: https://golangci-lint.run/usage/configuration/

version: "1"

run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
