# Minimale golangci-lint v2.x Konfiguration
# Siehe: https://golangci-lint.run/usage/configuration/

version: 2

run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
